### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by avidit**

### CODE REVIEW

**Comment by QilongTang** [comment]
@avidit Can you check the build error?

**Comment by avidit** [comment]
> @avidit Can you check the build error?

The action is trying to comment the PR with the code coverage summary. It seems it can't access the github-token. Can you please check if we have it enabled?
Or we can also skip the PR comment part
https://github.com/zgosalvez/github-actions-report-lcov#usage

**Comment by QilongTang** [comment]
> > @avidit Can you check the build error?
> 
> The action is trying to comment the PR with the code coverage summary. It seems it can't access the github-token. Can you please check if we have it enabled? Or we can also skip the PR comment part https://github.com/zgosalvez/github-actions-report-lcov#usage

I believe you need to set the `github-token`

**Comment by avidit** [comment]
> > > @avidit Can you check the build error?
> > 
> > 
> > The action is trying to comment the PR with the code coverage summary. It seems it can't access the github-token. Can you please check if we have it enabled? Or we can also skip the PR comment part [zgosalvez/github-actions-report-lcov#usage](https://github.com/zgosalvez/github-actions-report-lcov#usage)
> 
> I believe you need to set the `github-token`, we have a dynamo-ci bot I remember, maybe we need to set the token from that account so that bot user can comment

I have removed the PR comment part for now.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
