### PR TITLE
Update Version

### PR DESCRIPTION
**Pull request by QilongTang**
Update release version so npm packing can proceed

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@QilongTang did you also update the license files for the most recent release? We never automated that if I am recalling correctly. Sorry.

**Comment by QilongTang** [comment]
> @QilongTang did you also update the license files for the most recent release (see readme)? We never automated that if I am recalling correctly. Sorry.

The commands seems to be failing for me with/without VPN

**Comment by mjkkirschner** [comment]
thats a bummer - I don't have bandwidth to look into it now, if you have time please file a task - I think there was also a task to make it automated - maybe we can combine them?

**Comment by QilongTang** [comment]
> thats a bummer - I don't have bandwidth to look into it now, if you have time please file a task - I think there was also a task to make it automated - maybe we can combine them?

image

@mjkkirschner Does this error time out ring a bell to you? I tried both with/without VPN same error

**Comment by mjkkirschner** [comment]
I don't think that package exists on the public registry... shouldn't it be:
`https://npm.autodesk.com/artifactory/api/npm/autodesk-npm-virtual` ?

**Pull request merged**
