### PR TITLE
DYN-5816 Displaying the proper info according to the language

### PR DESCRIPTION
**Pull request by jesusalvino**
Purpose

Displaying the proper info according to the language, remove default values and update the tests | improvement https://jira.autodesk.com/browse/DYN-5816

Reviewers
@QilongTang
@reddyashish

FYIs
@RobertGlobant20
@Enzo707

### CODE REVIEW

**Comment by QilongTang** [comment]
@jesusalvino I think these changes are made so that when ppl build this repo alone, they can see the splash screen working with some baseline resources. If we remove the defaults, what would it display?

**Comment by jesusalvino** [comment]
> 



> @jesusalvino I think these changes are made so that when ppl build this repo alone, they can see the splash screen working with some baseline resources. If we remove the defaults, what would it display?

@QilongTang Ok, I will return those values and dealing with them in our side, just want to confirm if is necessary  set the ''

> @jesusalvino I think these changes are made so that when ppl build this repo alone, they can see the splash screen working with some baseline resources. If we remove the defaults, what would it display?



> @jesusalvino I think these changes are made so that when ppl build this repo alone, they can see the splash screen working with some baseline resources. If we remove the defaults, what would it display?

@QilongTang The default Title was reverted so each particular consumer can handle it, in the Dynamo project it's being handling through the bundle.

**Comment by jesusalvino** [comment]
> 



> @jesusalvino I think these changes are made so that when ppl build this repo alone, they can see the splash screen working with some baseline resources. If we remove the defaults, what would it display?

@QilongTang The default title was reverted so each particular consumer can handle it, in the Dynamo project it's being handling through the bundle.

**Comment by QilongTang** [comment]
Please bump up package version

**Review by QilongTang — APPROVED** [review]

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
